### PR TITLE
Modified project so that it can be uploaded to Maven.

### PR DESCRIPTION
**Pull request by ReedOei**
Project can now be uploaded to Maven central.

Deleted files: none.

Modified files:
```
/deploy-impact.sh
/dt-fixer/build.xml
/dt-impact-tracer/build.xml
```

Added files:
```
/pom.xml
/dt-fixer/pom.xml
/dt-impact-tracer/pom.xml
```

Also moved source files to standard Maven location.

### CODE REVIEW

**Comment by winglam** [comment]
Why did you have to add dt-fixer/libs/xstream-1.4.10.jar?

**Comment by winglam** [comment]
The modifications to dt-fixer/ should also have been unnecessary since dt-impact and dt-fixer are two separate projects. Nevertheless, the change does help future-proof the dt-fixer project if we ever decide to further pursue that project. Thanks for your work.

**Comment by ReedOei** [comment]
Before I added xstream-1.4.10.jar I was getting this error when trying to build (and a similar error when trying to build with Maven).

```
Buildfile: /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/build.xml

build-subprojects:

init:
    [mkdir] Created dir: /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/bin

build-project:
     [echo] dt-fixer: /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/build.xml
    [javac] Compiling 4 source files to /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/bin
    [javac] /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/src/main/java/edu/washington/cs/dt/fixer/Main/InstrumentationMain.java:23: error: package com.thoughtworks.xstream does not exist
    [javac] import com.thoughtworks.xstream.XStream;
    [javac]                                ^
    [javac] /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/src/main/java/edu/washington/cs/dt/fixer/Main/InstrumentationMain.java:24: error: package com.thoughtworks.xstream.io.xml does not exist
    [javac] import com.thoughtworks.xstream.io.xml.StaxDriver;
    [javac]                                       ^
    [javac] /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/src/main/java/edu/washington/cs/dt/fixer/Main/InstrumentationMain.java:94: error: cannot find symbol
    [javac]                 XStream xstream = new XStream(new StaxDriver());
    [javac]                 ^
    [javac]   symbol:   class XStream
    [javac]   location: class InstrumentationMain
    [javac] /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/src/main/java/edu/washington/cs/dt/fixer/Main/InstrumentationMain.java:94: error: cannot find symbol
    [javac]                 XStream xstream = new XStream(new StaxDriver());
    [javac]                                       ^
    [javac]   symbol:   class XStream
    [javac]   location: class InstrumentationMain
    [javac] /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/src/main/java/edu/washington/cs/dt/fixer/Main/InstrumentationMain.java:94: error: cannot find symbol
    [javac]                 XStream xstream = new XStream(new StaxDriver());
    [javac]                                                   ^
    [javac]   symbol:   class StaxDriver
    [javac]   location: class InstrumentationMain
    [javac] /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/src/main/java/edu/washington/cs/dt/fixer/Main/InstrumentationMain.java:147: error: cannot find symbol
    [javac]             XStream xstream = new XStream(new StaxDriver());
    [javac]             ^
    [javac]   symbol:   class XStream
    [javac]   location: class InstrumentationMain
    [javac] /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/src/main/java/edu/washington/cs/dt/fixer/Main/InstrumentationMain.java:147: error: cannot find symbol
    [javac]             XStream xstream = new XStream(new StaxDriver());
    [javac]                                   ^
    [javac]   symbol:   class XStream
    [javac]   location: class InstrumentationMain
    [javac] /home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/src/main/java/edu/washington/cs/dt/fixer/Main/InstrumentationMain.java:147: error: cannot find symbol
    [javac]             XStream xstream = new XStream(new StaxDriver());
    [javac]                                               ^
    [javac]   symbol:   class StaxDriver
    [javac]   location: class InstrumentationMain
    [javac] 8 errors

BUILD FAILED
/home/roei/Dropbox/Programming/Java/dependent-tests-impact/dt-fixer/build.xml:47: Compile failed; see the compiler error output for details.

Total time: 0 seconds

```

**Comment by ReedOei** [comment]
Also, as far as dt-fixer goes then, should I change it so that each project is independent of each other? Right now I have it so that both dt-fixer and dt-impact-tracer are modules in the main project?

**Comment by winglam** [comment]
I see. Dt-fixer may have already been broken even before you looked into it then. Thanks for fixing the build error in this case.

As for "canning" it, don't undo your changes to setup dt-fixer but please make it so that there is a way to build only dt-impact and update dt-impact's Maven version without needing to do anything with dt-fixer.

**Comment by ReedOei** [comment]
Okay. It is possible to build only one module by just using `mvn package -pl dt-impact-tracer`, or by simply running `mvn package` inside of the directory for whichever module you want to build. Is that sufficient?

**Comment by winglam** [comment]
Yeah, that would be sufficient. Thanks for your work!

**Pull request merged**
